'use client';
import {useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {ArrowDownToLine,RefreshCw,Search,Save,ArrowUpRight,FlaskConical,LockKeyhole,ChevronRight} from 'lucide-react';
import livePolicy from '@/data/live-policy.json';
import {liveForecast,validateObservations} from '@/lib/live.mjs';
import {CardArtwork,japaneseCardImage} from '@/components/card-artwork';
import type {Card,Forecast,Saved} from '@/lib/types';
const rarity:Record<string,string>={common:'コモン',uncommon:'アンコモン',rare:'レア',mythic:'神話レア'};
const colors:Record<string,string>={W:'白',U:'青',B:'黒',R:'赤',G:'緑',C:'無色',M:'多色'};
const pairNames:Record<string,string>={WU:'白青',WB:'白黒',WR:'白赤',WG:'白緑',UB:'青黒',UR:'青赤',UG:'青緑',BR:'黒赤',BG:'黒緑',RG:'赤緑'};
const time=(s:string)=>new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const f=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
function download(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Panel({children,className='',id}:{children:React.ReactNode,className?:string,id?:string}){return <section id={id} className={'rounded-xl border border-border bg-card '+className}>{children}</section>}
function PredictionReason({card}:{card:Card}){return <div className="space-y-6">{card.phase&&card.phase!=='PREVIEW'&&<section className="p-4 rounded-lg bg-accent/40 text-sm leading-7"><h3 className="font-semibold mb-2">ライブ推定と実測</h3><p>GIH WR：ライブ {f(card.gih,2)}% / 実測 {card.observed_gih==null?'未取得':f(card.observed_gih,2)+'%'}（#GIH {card.observed_gih_n?.toLocaleString()||0}）</p><p>ALSA：ライブ {f(card.alsa,2)}手 / 実測 {card.observed_alsa==null?'未取得':f(card.observed_alsa,2)+'手'}（#Seen {card.observed_seen_n?.toLocaleString()||0}）</p><p>実測反映率：GIH {f((card.gih_observation_weight||0)*100)}% / ALSA {f((card.alsa_observation_weight||0)*100)}%</p><p>セット全体の補正 {f(card.set_bias_adjustment||0,2)}pt / カード単位の補正 {f(card.card_bias_adjustment||0,2)}pt</p><p>実測−発売前予測：GIH {card.gih_error==null?'—':f(card.gih_error,2)+'pt'} / ALSA {card.alsa_error==null?'—':f(card.alsa_error,2)+'手'}</p>{card.source_timestamp&&<p>実測取得：{time(card.source_timestamp)}</p>}{card.late_card&&<p>凍結後の追加カード：発売前予測はありません。</p>}</section>}{(['gih','alsa'] as const).map(t=>{const e=t==='gih'?card.gih_explanation:undefined;return <section key={t}><h3 className="text-lg font-semibold text-primary">{t==='gih'?'GIH WR':'ALSA'}：{f(t==='gih'?(card.pre_release_gih??card.gih):card.alsa,2)}{t==='gih'?'%':'手'}（{card.late_card?'追加後の参考値':'発売前'}）</h3>{t==='alsa'?null:e?<><dl className="mt-3 space-y-2 text-sm">{([['base','モデルの基準値'],['card','マナ・サイズ・能力など'],['text','ルールテキストの語句'],['context','公開カードの構成'],['clipping','予測範囲の補正']] as const).filter(([k])=>t==='alsa'||k!=='context').map(([k,label])=><div key={k} className="flex justify-between gap-4"><dt>{label}</dt><dd className="number">{e[k]>=0?'+':''}{f(e[k],2)}{t==='gih'?'pt':'手'}</dd></div>)}</dl><details className="mt-3"><summary className="text-sm text-primary cursor-pointer">主な特徴の内訳</summary>{e.terms.map((r,i)=><div className="flex justify-between gap-3 text-sm py-1" key={i}><span>{r.label}</span><span>{r.value>=0?'+':''}{f(r.value,2)}{t==='gih'?'pt':'手'}</span></div>)}</details></>:<p className="text-sm mt-3">旧保存版の寄与：{card[t==='gih'?'gih_reason':'alsa_reason'].map(r=>`${r.label} ${f(r.value,2)}`).join(' / ')}</p>}</section>})}<p className="text-sm text-muted-foreground leading-6">数値は学習モデルの加減算です。能力そのものの因果効果や、人間によるカード評価を表すものではありません。</p></div>}
export default function Home(){
 const [reasonOpen,setReasonOpen]=useState(false),[auto,setAuto]=useState(true);
 const [data,setData]=useState<{forecast:Forecast;summary:{alsa_mae:number};live_status?:any;snapshots:Saved[];viewing?:any}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[tab,setTab]=useState('cards'),[query,setQuery]=useState(''),[color,setColor]=useState('all'),[rare,setRare]=useState('all'),[sort,setSort]=useState('gih'),[selected,setSelected]=useState<string|null>(null),[saveOpen,setSaveOpen]=useState(false),[label,setLabel]=useState(''),[compare,setCompare]=useState<{label:string;cards:Card[]}|null>(null);
 async function load(id?:string){const r=await fetch(import.meta.env.BASE_URL+'forecast.json',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'読み込めませんでした。');
 try{const res=await fetch(import.meta.env.BASE_URL+'live/fra-public-game.json',{cache:'no-store'});
  if(res.ok){const result=await res.json();const url='https://17lands-public.s3.amazonaws.com/analysis_data/game_data/game_data_public.FRA.PremierDraft.csv.gz';
   const o=result.observations;if(result.status==='available'&&result.dataset_url===url&&o?.sources?.game?.url===url&&Object.keys(o.sources).join(',')==='game'&&o.cards?.every((c:any)=>c.alsa==null&&!(c.alsa_n>0))&&validateObservations(o)&&o.cards.some((c:any)=>c.gih_n>0)){
    d.forecast=liveForecast(d.forecast,o,livePolicy.policies.current);d.live_status={check:{checked_at:result.checked_at},sync:{error:false}};
   }else if(result.checked_at)d.live_status={check:{checked_at:result.checked_at},sync:{error:result.status==='error'}};
  }
 }catch{ /* Dataset check failures retain the last valid prediction. */ }
 setData(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!auto||data?.viewing)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{});},300000);return()=>clearInterval(timer);},[auto,data?.viewing,busy,saveOpen]);
 useEffect(()=>{if(data?.viewing)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{});},900000);return()=>clearInterval(timer);},[data?.viewing]);
 async function action(body:any){setNotice('GitHub Pages版では公式カード更新・予測保存は利用できません。');return false;}
 const cards=data?.forecast.cards||[];
 const filtered=useMemo(()=>cards.filter(c=>(c.name+' '+(japaneseCardImage(c)?.name_ja||'')+' '+c.oracle_text+' '+c.type_line).toLowerCase().includes(query.toLowerCase())&&(rare==='all'||c.rarity===rare)&&(color==='all'||(color==='C'?c.colors.length===0:color==='M'?c.colors.length>1:c.colors.includes(color)))).sort((a,b)=>sort==='alsa'?a.alsa-b.alsa:sort==='name'?a.name.localeCompare(b.name):sort==='cmc'?a.cmc-b.cmc:b.gih-a.gih),[cards,query,rare,color,sort]);
 const card=cards.find(c=>c.id===selected)||filtered[0];const base=new Map(compare?.cards.map(c=>[c.name,c])||[]);
 function exportData(kind:'csv'|'md') {const clean=(s:string)=>s.replace(/[\r\n|]/g,' ');if(kind==='csv'){const cell=(v:string)=>'"'+(/^[=+\-@]/.test(v)?"'":'')+v.replaceAll('"','""')+'"';download('\uFEFF'+[['Card','Rarity','Colors','Mana value','Estimated GIH WR (%)','GIH lower','GIH upper','Estimated ALSA','ALSA lower','ALSA upper','Forecast date','Model','Phase','Pre-release GIH','Observed GIH','GIH N','GIH observation weight','Pre-release ALSA','Observed ALSA','Seen N','ALSA observation weight','Observation date'],...filtered.map(c=>[c.name,c.rarity,c.colors.join(''),c.cmc,f(c.gih,2),...c.gih_range.map(n=>f(n,2)),f(c.alsa,2),...c.alsa_range.map(n=>f(n,2)),data!.forecast.retrieved_at,data!.forecast.model_version,c.phase||'PREVIEW',c.pre_release_gih??(c.late_card?'':c.gih),c.observed_gih??'',c.observed_gih_n||0,c.gih_observation_weight||0,c.pre_release_alsa??(c.late_card?'':c.alsa),c.observed_alsa??'',c.observed_seen_n||0,c.alsa_observation_weight||0,c.source_timestamp||''])].map(r=>r.map(v=>cell(String(v))).join(',')).join('\r\n'),'FRA-premier-forecast.csv','text/csv;charset=utf-8');}else{download('# リアリティ・フラクチャー：Premier Draft予測\n\n予測基準日: '+data!.forecast.retrieved_at+' / '+data!.forecast.model_version+'\n\n対象はArena提供開始から28日間。以下の主表示は予測またはライブ推定で、実測値そのものではありません。学習元: [17Lands公開データ](https://www.17lands.com/public_datasets)。\n\n|カード|予測GIH WR|予測ALSA|\n|---|---:|---:|\n'+filtered.map(c=>`|${clean(c.name)}|${f(c.gih)}%|${f(c.alsa,2)}|`).join('\n')+'\n\n## 個別メモ\n\n'+filtered.map(c=>`### ${clean(c.name)}\n\n予測GIH WR ${f(c.gih)}%、予測ALSA ${f(c.alsa,2)}。過去の類似カード: ${c.similar.map(s=>`${s.name}（${s.set}、GIH WR ${f(s.gih)}%、ALSA ${f(s.alsa,2)}）`).join(' / ')}。\n\n${c.note}\n`).join('\n'),'FRA-note-material.md','text/markdown;charset=utf-8');}}
 function selectCard(id:string){setSelected(id);setReasonOpen(true);}
 if(!data)return <main className="max-w-5xl mx-auto p-8"><p className="text-primary text-sm tracking-widest">YAMABE KAFKA / LIMITED RESEARCH</p><h1 className="text-3xl font-semibold mt-4">Limited Forecast</h1><Panel className="mt-8 p-8"><p role="status">{error||'予測データを読み込んでいます…'}</p>{error&&<Button className="mt-4" onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>再試行</Button>}</Panel></main>;
 return <main className="max-w-[1600px] mx-auto px-4 sm:px-8 lg:px-12 pb-16">
  <header className="flex items-center justify-between py-6 border-b border-border gap-4"><a href={import.meta.env.BASE_URL} className="flex items-center gap-3"><FlaskConical className="text-primary size-7"/><span className="font-semibold text-xl tracking-tight">Limited Forecast</span></a><span className="text-sm text-muted-foreground hidden sm:block">山辺カフカ / リミテッド研究室</span><span className="border border-primary/30 text-primary rounded-full px-3 py-1 text-xs">{data.forecast.phase==='OBSERVED_DOMINANT'?'実測が十分に蓄積':data.forecast.phase==='EARLY_DATA'?'実測を反映中':'発売前予測'}</span></header>
  <section className="pt-8 pb-6 flex flex-wrap gap-5 items-end justify-between"><div><p className="text-primary text-sm mb-2 tracking-widest">REALITY FRACTURE · FRA</p><h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">リアリティ・フラクチャー</h1><p className="text-muted-foreground text-sm mt-3">Premier Draft / BO1 · 発売後28日間 · 公開データ母集団</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={true} onClick={()=>action({action:'refresh'})}><RefreshCw className={busy==='refresh'?'animate-spin':''}/>公開カードを更新</Button><Button disabled={true} onClick={()=>{setLabel('FRA予測 '+time(new Date().toISOString()));setSaveOpen(true)}}><Save/>予測を保存</Button></div></section>
  <div className="flex flex-wrap gap-3 items-center mb-4 text-sm"><Button variant="outline" size="sm" aria-pressed={auto} onClick={()=>setAuto(!auto)}>自動更新：{auto?'ON':'OFF'}</Button><span className="text-muted-foreground">表示中は5分ごとに更新確認。公式確認：{time(data.forecast.checked_at||data.forecast.retrieved_at)}</span></div>
  <div className="mb-5 text-sm text-muted-foreground leading-6" role="status"><p>17Lands Public Datasetはデータリポジトリで1日1回自動確認{data.live_status?.check?.checked_at&&` · 最終確認 ${time(data.live_status.check.checked_at)}`}</p><p>{data.live_status?.sync?.error||data.live_status?.check?.error?'自動確認結果の取得に失敗しました。現在の値を維持しています。':data.forecast.phase&&data.forecast.phase!=='PREVIEW'?'Game Dataの実測を反映中 · 発売前予測は保存済み':'公開データが利用可能になるまで発売前予測を維持'}</p></div>
  <p className="text-sm text-muted-foreground mb-6">学習データ：<a href="https://www.17lands.com/public_datasets" target="_blank" rel="noreferrer" className="text-primary underline underline-offset-4">17Lands公開データ（CC BY 4.0）</a> · カード情報：<a href="https://magic.wizards.com/en/products/reality-fracture/card-image-gallery" target="_blank" rel="noreferrer" className="underline underline-offset-4">Wizards公式</a> / Scryfall</p>
  {error&&<div role="alert" className="mb-5 border border-red-400/40 bg-red-400/10 text-red-200 p-4 rounded-lg">{error}</div>}{notice&&<div role="status" className="mb-5 text-primary">{notice}</div>}
  {data.viewing&&<div className="mb-5 flex flex-wrap justify-between items-center gap-3 p-4 border border-primary/40 rounded-lg"><span>保存版を表示中：{data.viewing.label} {data.viewing.frozen?'（固定済み）':''}</span><Button variant="outline" onClick={()=>load().catch(e=>setError(e.message))}>現在の予測に戻る</Button></div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-7">
   <Panel className="p-5"><p className="text-sm text-muted-foreground">取り込み済み公開カード</p><p className="text-3xl mt-3 number">{cards.length}<span className="text-sm text-muted-foreground ml-2">種</span></p></Panel>
   {(['gih','alsa'] as const).map(t=><Panel key={t} className="p-5"><p className="text-sm text-muted-foreground">{t==='gih'?'GIH WR・22セットLOSO':'ALSA'}の検証誤差（MAE）</p><p className="text-3xl mt-3 number">{f(t==='gih'?2.5120870952804992:data.summary.alsa_mae,2)}<span className="text-sm text-muted-foreground ml-2">{t==='gih'?'pt':'手'}</span></p></Panel>)}
   <Panel className="p-5"><p className="text-sm text-muted-foreground">公式カード最終確認（日本時間）</p><p className="text-xl mt-4 number">{time(data.forecast.checked_at||data.forecast.retrieved_at)}</p></Panel>
  </div>
  <Tabs value={tab} onValueChange={setTab}>
   <TabsList className="bg-transparent border-b border-border rounded-none h-12 w-full justify-start gap-6 mb-6"><TabsTrigger value="cards" className="px-0 rounded-none data-[state=active]:bg-transparent data-[state=active]:text-primary">カード予測</TabsTrigger><TabsTrigger value="deck-color" className="px-0 rounded-none data-[state=active]:bg-transparent data-[state=active]:text-primary">色別勝率予測</TabsTrigger><TabsTrigger value="history" className="px-0 rounded-none data-[state=active]:bg-transparent data-[state=active]:text-primary">保存した予測 <span className="ml-1 text-muted-foreground">{data.snapshots.length}</span></TabsTrigger></TabsList>
   <TabsContent value="cards">
    <div className="flex flex-wrap items-center gap-3 mb-4"><div className="relative flex-1 min-w-52"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input aria-label="カード名・テキストを検索" placeholder="カード名・テキストを検索" value={query} onChange={e=>setQuery(e.target.value)} className="pl-10 h-10"/></div><NativeSelect aria-label="レアリティ" value={rare} onChange={e=>setRare(e.target.value)}><NativeSelectOption value="all">全レアリティ</NativeSelectOption>{Object.entries(rarity).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect><NativeSelect aria-label="並び順" value={sort} onChange={e=>setSort(e.target.value)}><NativeSelectOption value="gih">GIH WRの高い順</NativeSelectOption><NativeSelectOption value="alsa">ALSAの低い順</NativeSelectOption><NativeSelectOption value="cmc">マナ総量順</NativeSelectOption><NativeSelectOption value="name">名前順</NativeSelectOption></NativeSelect></div>
    <div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div className="flex flex-wrap gap-1">{[['all','すべて'],...Object.entries(colors)].map(([k,v])=><Button key={k} size="sm" variant={color===k?'secondary':'ghost'} aria-pressed={color===k} onClick={()=>setColor(k)}>{v}</Button>)}</div><div className="flex flex-wrap gap-1"><Button variant="ghost" size="sm" onClick={()=>exportData('csv')}><ArrowDownToLine/>CSV</Button><Button variant="ghost" size="sm" onClick={()=>exportData('md')}><ArrowDownToLine/>記事用Markdown</Button></div></div>
    {compare&&<div className="mb-4 text-sm flex gap-3 items-center">比較先：{compare.label}<Button size="sm" variant="ghost" onClick={()=>setCompare(null)}>比較を解除</Button></div>}
    <p className="text-sm text-primary mb-3">カード名をクリックすると、日本語カード画像とGIH WR・ALSAの予測理由が開きます。</p>
    <p className="text-sm text-muted-foreground mb-4">{filtered.length}件 · 数値は予測です。幅は過去セットの誤差から算出した目安で、FRAの実測値・保証値ではありません。</p>
    {!!data.forecast.change_summary?.changes?.length&&<details className="mb-5 rounded-lg border border-border p-4"><summary className="cursor-pointer text-sm text-primary">直近の更新：新規{data.forecast.change_summary.added||0}枚・既存変更{data.forecast.change_summary.revised||0}枚（{time(data.forecast.change_summary.at)}）</summary><div className="max-h-72 overflow-auto mt-3">{data.forecast.change_summary.changes.map(c=><p key={c.name} className="text-sm py-1">{c.name}：{c.kind==='added'?`新規 GIH ${f(c.gih)}% / ALSA ${f(c.alsa,2)}`:`${c.kind==='context'?'公開カード構成の変化':'カード情報の修正'} → GIH ${c.gih>=0?'+':''}${f(c.gih,2)}pt / ALSA ${c.alsa>=0?'+':''}${f(c.alsa,2)}手`}</p>)}</div></details>}
    <div className="grid lg:grid-cols-[minmax(0,1fr)_360px] xl:grid-cols-[minmax(0,1fr)_400px] gap-5 items-start">
     <Panel id="cards-table" className="overflow-hidden"><Table><TableHeader><TableRow><TableHead className="pl-5">カード</TableHead><TableHead className="text-right">{data.forecast.phase&&data.forecast.phase!=='PREVIEW'?'ライブGIH WR':'予測GIH WR'}</TableHead><TableHead className="text-right">{data.forecast.phase&&data.forecast.phase!=='PREVIEW'?'ライブALSA':'予測ALSA'}</TableHead><TableHead className="w-6"><span className="sr-only">詳細</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(c=>{const b=base.get(c.name);return <TableRow key={c.id} className={'cursor-pointer hover:bg-accent/50 '+(card?.id===c.id?'bg-accent/60':'')} onClick={()=>selectCard(c.id)}><TableCell className="pl-5 py-4 max-w-72"><button onClick={()=>selectCard(c.id)} className="font-medium text-left whitespace-normal focus-visible:outline-2 focus-visible:outline-primary">{c.name}</button><div className="text-xs text-muted-foreground mt-1.5">{c.mana_cost||'土地'} · {rarity[c.rarity]}{c.manual?' · 手動':''}</div></TableCell><TableCell className="text-right number"><span className="font-semibold text-primary text-lg">{f(c.gih)}<span className="text-xs">%</span></span><div className="text-xs text-muted-foreground mt-1">{c.phase&&c.phase!=='PREVIEW'?`発売前 ${f(c.pre_release_gih??NaN)}%`:`${f(c.gih_range[0])}–${f(c.gih_range[1])}%`}</div>{b&&<div className="text-xs mt-1">差 {c.gih-b.gih>=0?'+':''}{f(c.gih-b.gih)}pt</div>}</TableCell><TableCell className="text-right number"><span className="text-lg">{f(c.alsa,2)}</span><div className="text-xs text-muted-foreground mt-1">{c.phase&&c.phase!=='PREVIEW'?`発売前 ${f(c.pre_release_alsa??NaN,2)}`:`${f(c.alsa_range[0],1)}–${f(c.alsa_range[1],1)}`}</div>{b&&<div className="text-xs mt-1">差 {c.alsa-b.alsa>=0?'+':''}{f(c.alsa-b.alsa,2)}</div>}</TableCell><TableCell><ChevronRight className="size-4 text-muted-foreground"/></TableCell></TableRow>})}</TableBody></Table>{!filtered.length&&<p className="p-8 text-muted-foreground">該当するカードがありません。検索条件を変更してください。</p>}</Panel>
     {card&&<Panel id="card-detail" className="p-5 lg:sticky lg:top-5 max-h-none lg:max-h-[calc(100vh-40px)] lg:overflow-y-auto"><div className="flex justify-between items-start gap-3"><div><Button variant="ghost" size="sm" className="lg:hidden mb-3" onClick={()=>document.getElementById('cards-table')?.scrollIntoView({behavior:'smooth'})}>一覧へ戻る</Button><p className="text-xs text-primary tracking-wider mb-2">CARD DETAIL</p><h2 className="font-semibold text-xl">{card.name}</h2></div></div><p className="text-sm text-muted-foreground mt-3">{card.mana_cost} · {card.type_line}</p><p className="mt-4 text-sm whitespace-pre-wrap leading-7">{card.oracle_text}</p>{card.power&&<p className="text-right mt-2 number">{card.power} / {card.toughness}</p>}<a href={card.source.startsWith('https://')?card.source:'https://magic.wizards.com/en/products/reality-fracture/card-image-gallery'} target="_blank" rel="noreferrer" className="text-primary text-sm inline-flex items-center gap-1 mt-4">カード情報の出典<ArrowUpRight className="size-4"/></a>
      <div className="border-t border-border mt-5 pt-5 mb-5"><h3 className="font-medium mb-3">この予測になった理由</h3><PredictionReason card={card}/></div>
      <div className="border-t border-border pt-5"><h3 className="font-medium mb-3">過去の類似カード</h3>{card.similar.map((s,i)=><a key={i} href={s.source} target="_blank" rel="noreferrer" className="block py-3 border-b border-border last:border-0"><p className="text-sm">{s.name}<ArrowUpRight className="inline size-3 ml-1"/></p><p className="text-xs text-muted-foreground mt-1">{s.set} · 実績GIH {f(s.gih)}% / ALSA {f(s.alsa,2)}</p><p className="text-xs text-muted-foreground mt-1">GIH件数 {s.gih_n?.toLocaleString()} / パック件数 {s.alsa_n?.toLocaleString()}</p></a>)}</div></Panel>}
    </div>
   </TabsContent>
   <TabsContent value="deck-color"><p className="text-sm text-muted-foreground mb-4">Premier Draft・タッチなし2色の発売前予測。Two-color平均は各色組の予測勝率の平均です。</p><Panel className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="pl-5">順位</TableHead><TableHead>色組</TableHead><TableHead className="text-right">予測勝率</TableHead><TableHead className="text-right">Two-color平均との差</TableHead><TableHead className="text-right pr-5">80%誤差目安</TableHead></TableRow></TableHeader><TableBody>{data.forecast.deck_color?.rows.map(row=><TableRow key={row.pair}><TableCell className="pl-5 number">{row.rank}</TableCell><TableCell className="font-medium">{pairNames[row.pair]}</TableCell><TableCell className="text-right number text-primary">{f(row.predicted_wr_pct)}%</TableCell><TableCell className="text-right number">{row.delta_pp>=0?'+':''}{f(row.delta_pp)}pt</TableCell><TableCell className="text-right pr-5 number">{f(row.range80[0])}–{f(row.range80[1])}%</TableCell></TableRow>)}</TableBody></Table>{!data.forecast.deck_color?.rows.length&&<p className="p-6 text-sm text-muted-foreground">予測を準備しています。</p>}</Panel></TabsContent>
   <TabsContent value="history"><Panel className="p-6"><h2 className="text-xl font-semibold mb-3">保存した予測</h2><p className="text-sm text-muted-foreground mb-6">保存時のカード情報・予測値・モデル版を保持します。公開カードを更新しても保存版は変わりません。「固定」は発売前の確定版の目印です。</p>{!data.snapshots.length?<p className="py-8 text-muted-foreground">まだ保存されていません。「予測を保存」から記録できます。</p>:<div className="space-y-3">{data.snapshots.map(s=><div key={s.id} className="flex flex-wrap gap-3 justify-between items-center border border-border rounded-lg p-4"><div><p>{s.label}{!!s.frozen&&<LockKeyhole className="inline ml-2 text-primary size-4"/>}</p><p className="text-xs text-muted-foreground mt-1">{time(s.created_at)}</p></div><div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" onClick={()=>load(s.id).then(()=>setTab('cards')).catch(e=>setError(e.message))}>表示</Button>{!s.frozen&&<Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>action({action:'freeze',id:s.id})}>固定</Button>}</div></div>)}</div>}</Panel></TabsContent>
  </Tabs>
  <footer className="mt-10 pt-6 border-t border-border text-xs text-muted-foreground leading-6">Limited Forecast · 非公式の研究ツールです。17LandsおよびWizards of the Coastによる承認・保証はありません。<br/>カード情報 © Wizards of the Coast · データの再集計・モデル化：Limited Forecast</footer>
  <Dialog open={reasonOpen} onOpenChange={setReasonOpen}><DialogContent className="sm:max-w-4xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle className="pr-6">{card&&(japaneseCardImage(card)?.name_ja||card.name)}</DialogTitle><DialogDescription>日本語カード画像・GIH WR・ALSAの予測理由</DialogDescription></DialogHeader>{card&&<div className="grid md:grid-cols-[minmax(0,340px)_minmax(0,1fr)] gap-6 items-start"><CardArtwork key={card.id} card={card}/><PredictionReason card={card}/></div>}</DialogContent></Dialog>
  <Dialog open={saveOpen} onOpenChange={setSaveOpen}><DialogContent><DialogHeader><DialogTitle>予測を保存</DialogTitle><DialogDescription>現在の予測値を日時・モデル版と一緒に記録します。</DialogDescription></DialogHeader><label className="text-sm">保存名<Input className="mt-2" value={label} maxLength={100} onChange={e=>setLabel(e.target.value)}/></label><Button disabled={!!busy||!label.trim()} onClick={async()=>{if(await action({action:'save',label:label.trim()}))setSaveOpen(false)}}>保存する</Button></DialogContent></Dialog>
 </main>;
}
